### ISSUE TITLE
Error: No model was found for 'toString'

### ISSUE THREAD

**Issue by pendar747** [kurko/ember-json-api#33]
I keep getting this error although I receive valid json api responses from the server.

example:
{"locations": [{"id":166,"lat":"51.4986658","lng":"-0.0593145","name":null,"type":null,"hyperlocation":null,"created_at":"2014-09-19T00:00:00+0100","updated_at":"2014-09-19T00:00:00+0100","distance":"0.0007320925290059726"}]}

this is the full error description:
Error: No model was found for 'toString'
    at new Error (native)
    at Error.EmberError (http://localhost/feelatlas/web/js/libs/ember.js:2965:23)
    at DS.Store.Ember.Object.extend.modelFor (http://localhost/feelatlas/web/js/libs/ember-data.js:2979:29)
    at DS.RESTSerializer.DS.JSONSerializer.extend.extractArray (http://localhost/feelatlas/web/js/libs/ember-data.js:8726:24)
    at apply (http://localhost/feelatlas/web/js/libs/ember.js:7996:27)
    at superWrapper (http://localhost/feelatlas/web/js/libs/ember.js:7570:15)
    at DS.JSONSerializer.Ember.Object.extend.primaryKey [as extractFindQuery] (http://localhost/feelatlas/web/js/libs/ember-data.js:92:29)
    at DS.JSONSerializer.Ember.Object.extend.extract (http://localhost/feelatlas/web/js/libs/ember-data.js:549:33)
    at http://localhost/feelatlas/web/js/libs/ember-data.js:3561:26
    at invokeCallback (http://localhost/feelatlas/web/js/libs/ember.js:10558:19)

**Comment by jonkoops** [comment]
I am closing this issue due to lack of activity and the impending deprecation in favour of the official Ember Data adapter. If you think this is an issue that relates to Ember Data please [report the issue](https://github.com/emberjs/data/issues/new) there.
