### ISSUE TITLE
Doesn't support an array of values

### ISSUE THREAD

**Issue by krainboltgreene** [kurko/ember-json-api#52]
Response:

``` json
{
    "accounts": [
        "2688051d-dcfa-42af-9c7b-72ac55192981"
    ],
    "meta": {
        "limit": 10,
        "filters": {},
        "includes": [],
        "fields": [
            "id"
        ]
    },
    "links": {},
    "linked": {}
}
```

The specification allowing this body: http://jsonapi.org/format/#document-structure-resource-collection-representations

> A collection of any number of resources SHOULD be represented as an array of resource objects **or IDs**, or as a single "collection object" (described below).

Emphasis mine.

ember-json-api error:

```
Error while processing route: index Assertion Failed: You must include an `id` for endorsemint@model:account: in an object passed to `push` Error: Assertion Failed: You must include an `id` for endorsemint@model:account: in an object passed to `push`
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:26712:23)
    at Object.Ember.assert (http://localhost:4200/assets/vendor.js:16896:15)
    at Ember.Object.extend.push (http://localhost:4200/assets/vendor.js:72942:15)
    at Ember.Object.extend.pushMany (http://localhost:4200/assets/vendor.js:73103:28)
    at http://localhost:4200/assets/vendor.js:73467:15
    at tryCatch (http://localhost:4200/assets/vendor.js:58992:16)
    at invokeCallback (http://localhost:4200/assets/vendor.js:59004:17)
    at publish (http://localhost:4200/assets/vendor.js:58975:11)
    at http://localhost:4200/assets/vendor.js:42243:9 
```

**Comment by jonkoops** [comment]
I am closing this issue due to lack of activity and the impending deprecation in favour of the official Ember Data adapter. If you think this is an issue that relates to Ember Data please [report the issue](https://github.com/emberjs/data/issues/new) there.
